---
galaxy_info:
  author: Israel Farfan
  description: Install Apache2
  company: IXF
  license: GPLv3
  min_ansible_version: 1.9.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
  - web

dependencies: []
