---
- import_tasks: install.yml
  tags: [postfix]

- import_tasks: config.yml
  tags: [postfix, postfix-config, provision]

- import_tasks: utils.yml
  tags: [postfix, postfix-utils]

- import_tasks: rsyslog.yml
  tags: [postfix, postfix-rsyslog, rsyslog]
