---
- name: Install Postfix + dependencies
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}
  with_items:
  - postfix
  - mailutils
  - libsasl2-2
  - ca-certificates
  - libsasl2-modules
