---
- name: Ensure Java is installed
  import_role:
    name: development/java_8

- name: Ensure Groovy is installed
  import_role:
    name: development/groovy

- import_tasks: install.yml
  tags: [gradle, gradle-install]

- import_tasks: path.yml
  tags: [gradle, gradle-path]
