---
- block:
  - name: Add PHP 5.6 repo
    apt_repository:
      repo='ppa:ondrej/php5-5.6'
      state=present

  - name: Install PHP 5.6
    apt:
      pkg={{ item }}
      state=present
      update_cache=yes
      cache_valid_time={{ apt_cache_time }}
    with_items: "{{ php_base_packages }}"

  tags: [php]

- block:
  - name: Install PHP extended packages
    apt:
      pkg={{ item }}
      state=present
      update_cache=yes
      cache_valid_time={{ apt_cache_time }}
    with_items: "{{ php_extended_packages }}"

  when: has_extended_packages
  tags: [php, php-extended]
