---
- block:
  - name: Rsyslog server /opt/logs
    file:
      path=/opt/logs
      state=directory
      owner=root
      group=root

  - name: Rsyslog server config
    template:
      src=etc/rsyslog.server.conf.j2
      dest=/etc/rsyslog.conf
      owner=root
      group=root
      mode=0644
    notify: reload rsyslog
  when: '"rsyslog" in group_names'

- name: Rsyslog client config
  template:
    src=etc/rsyslog.client.conf.j2
    dest=/etc/rsyslog.conf
    owner=root
    group=root
    mode=644
  when: '"rsyslog" not in group_names'
  notify: reload rsyslog

- name: Additional Rsyslog configs
  copy:
    src=etc/rsyslog.d/{{ item }}
    dest=/etc/rsyslog.d/
    owner=root
    group=root
    mode=0644
  with_items:
  - 00-common.conf
  - 21-cloudinit.conf
  - 50-default.conf
  notify: reload rsyslog
