---
java_oracle_pkgs:
- ca-certificates
- oracle-java8-installer
- oracle-java8-set-default

java_oracle_path: /usr/lib/jvm/oracle-java8-amd64
java_oracle_exec: "{{ java_oracle_path }}/bin/java"

java_openjdk_pkgs:
- ca-certificates-java
- openjdk-8-jre-headless

java_openjdk_path: /usr/lib/jvm/java-8-openjdk-amd64
java_openjdk_exec: "{{ java_openjdk_path }}/bin/java"

#  Use Oracle
oracle_version: false
