---
- name: Install Buildah
  block:

  - name: Install Buildah pre-requisites
    apt:
      pkg: "{{ buildah_required_pkgs }}"
      state: present
      update_cache: yes
      cache_valid_time: "{{ apt_cache_time }}"

  - name: Add Buildah repo
    apt_repository:
      repo: "{{ buildah_repo }}"
      state: present

  - name: Install Buildah
    apt:
      pkg: buildah
      state: present
      update_cache: yes
      cache_valid_time: "{{ apt_cache_time }}"

  tags: [buildah]
