---
- include: redis.yml
  tags: [redis]

# - include: redis_configs.yml
#   tags: [redis, redis-configs]

# - include: sysctl.yml
#   tags: [redis, redis-sysctl, sysctl]

# - include: logrotate.yml
#   tags: [redis, redis-logrotate, logrotate]

# - include: redis_utils.yml
#   tags: [redis, redis-utils]
