---
# Install pre-requisites
- name: Install pre-requisites packages
  apt:  pkg={{ item }} state=present
  with_items:
     - librack-ruby
     - rails
  notify:
     - flush cached-memory
     - run updatedb
  tags:
     - ruby
     - gdash

- name: Switch Ruby1.8 version
  shell: "/usr/bin/ruby-switch --set ruby1.8"
  notify: run updatedb
  tags:
     - ruby
     - gdash

- name: Install Gems Dependencies
  gem: name={{ item }} state=latest
  with_items:
     - rdoc
     - bundler
  notify: run updatedb
  tags:
     - ruby
     - gdash


# Install GDash
- name: Check for previous GDash install
  shell: "[ -d /opt/gdash ]"
  ignore_errors: yes
  register: gdash_folder
  tags: gdash

- name: Download GDash
  git: repo=https://github.com/ripienaar/gdash.git dest=/opt/gdash
  notify: run updatedb
  when: gdash_folder|failed
  tags: gdash

- name: Copy GDash config
  template: src={{ files_dir }}/opt/gdash/config/gdash.yaml.j2 dest=/opt/gdash/config/gdash.yaml owner=root group=root mode=0644
  notify:
     - reload apache
     - run updatedb
  tags:
     - gdash-configs
     - gdash

- name: Remove unneeded folders
  file: path=/opt/gdash/{{ item }} state=absent
  with_items:
     - .git
     - .gitignore
     - graph_templates/node_templates
  notify: run updatedb
  tags:
     - gdash-configs
     - gdash

- name: Create new folders
  file: path=/opt/gdash/{{ item }} state=directory owner=root group=root
  with_items:
     - tmp
     - graph_templates/servers
     - graph_templates/stats
  tags:
     - gdash-configs
     - gdash

- name: Copy tmp/restart.txt
  copy: src={{ files_dir }}/opt/gdash/tmp/restart.txt dest=/opt/gdash/tmp/ owner=root group=root mode=0644 backup=no
  notify: run updatedb
  tags:
     - gdash-configs
     - gdash

- name: Install GDash
  shell: bundle install --deployment chdir=/opt/gdash/ executable=/bin/bash
  ignore_errors: yes
  notify: run updatedb
  when: gdash_folder|failed
  tags: gdash


# Install Graph Generating Code
- name: Copy r29 folders
  copy: src={{ files_dir }}/opt/gdash/r29 dest=/opt/gdash/ owner=root group=root
  notify: run updatedb
  tags:
     - gdash-configs
     - gdash

- name: Chmod /bin folder
  file: path=/opt/gdash/r29/bin mode=0755 state=directory recurse=yes
  notify: run updatedb
  tags:
     - gdash-configs
     - gdash

- name: Remove DS_Store files
  shell: /usr/bin/find /opt/gdash/r29/ -name ".DS_Store" -depth -exec rm {} \;
  notify: run updatedb
  tags:
     - gdash-configs
     - gdash


# Enable Apache fronting
#
# READ: http://recipes.sinatrarb.com/p/deployment/apache_with_passenger
- name: Install mod-passenger
  apt:  pkg=libapache2-mod-passenger state=present
  notify:
     - reload apache
     - flush cached-memory
     - run updatedb
  tags:
     - apache
     - gdash

- name: Enable passenger
  command: a2enmod passenger creates=/etc/apache2/mods-enabled/passenger.load
  notify:
     - reload apache
     - run updatedb
  tags:
     - apache
     - gdash

- name: Copy GDash Apache conf
  copy: src={{ files_dir }}/etc/apache2/sites-available/gdash dest=/etc/apache2/sites-available/ owner=root group=root mode=0644 backup=no
  notify:
     - reload apache
     - run updatedb
  tags:
     - gdash-configs
     - apache
     - gdash

- name: Enable GDash site
  command: /usr/sbin/a2ensite gdash creates=/etc/apache2/sites-enabled/gdash
  notify:
     - reload apache
     - run updatedb
  tags:
     - apache
     - gdash
