---
- name: Install Apache Python libs
  apt:
    pkg={{ item }}
    state=installed
    install_recommends=no
    cache_valid_time=1800
    update_cache=yes
  with_items:
  - libapache2-mod-wsgi
  - libapache2-mod-python
  notify: reload apache

- name: Disable mod-python to prevent conflicts with wsgi
  command: >
    a2dismod python
    removes=/etc/apache2/mods-enabled/python.load
  notify: reload apache

- name: Copy Graphite Apache conf
  copy:
    src=etc/apache2/sites-available/graphite.conf
    dest=/etc/apache2/sites-available/
    owner=root
    group=root
    mode=0644
  notify: reload apache

- name: Enable Graphite site
  command: >
    a2ensite graphite.conf
    creates=/etc/apache2/sites-enabled/graphite.conf
  notify: reload apache
