---
- name: MySQL create graphite db
  mysql_db:
    name={{ graphite_sql_db }}
    state=present
    encoding=utf8
    collation=utf8_unicode_ci

- name: MySQL create graphite username
  mysql_user:
    host=localhost
    name={{ graphite_sql_usr }}
    password={{ graphite_sql_pwd }}
    priv={{ graphite_sql_db }}.*:ALL
    state=present

- name: Check if database is empty
  command: >
    mysql --database {{ graphite_sql_db }} -e "show tables like 'auth_user';"
  changed_when: False
  register: db_populated

- name: Sync database
  shell: >
    graphite-manage syncdb --noinput
    chdir=/usr/bin/
    executable=/bin/bash
  become: yes
  when: db_populated.stdout.find('auth_user') == -1
