---
- name: Find JAVA_HOME
  shell: >
    readlink -f $(which java)
    executable=/bin/bash
  changed_when: False
  register: java_path

- name: Set JAVA_HOME
  lineinfile:
    dest=/etc/environment
    state=present
    regexp='^JAVA_HOME'
    line='JAVA_HOME={{ java_path.stdout }}'

- name: Enable JAVA_HOME
  shell: >
    source /etc/environment
    executable=/bin/bash
  changed_when: False
