---
- name: Set automatic debconf selections
  debconf:
    name='oracle-java7-installer'
    question='shared/accepted-oracle-license-v1-1'
    vtype='select'
    value='true'

- name: Add Java 7 repo
  apt_repository:
    repo='ppa:webupd8team/java'
    state=present

- name: Install Java 7
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}
  with_items:
  - oracle-java7-installer
  - oracle-java7-set-default
