---
#===============================================================================
#
#  T A S K S / G R A P H I C S M A G I C K . Y M L
#
#  URL: http://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/
#
#===============================================================================
- name: Determine if graphicsmagick folder exists
  stat: path={{ graphicsmagick_location }}
  register: graphicsmagick_folder

- name: Download graphicsmagick
  get_url:
    url={{ graphicsmagick_url }}
    dest=/tmp/GraphicsMagick-{{ graphicsmagick_version }}.tar.gz
    mode=0440
  when: not graphicsmagick_folder.stat.exists

- name: Unpack and install graphicsmagick
  shell: |
    tar -zxvf GraphicsMagick-{{ graphicsmagick_version }}.tar.gz
    cd GraphicsMagick-{{ graphicsmagick_version }}
    ./configure LDFLAGS='-L{{ libjpeg_location }}/lib64 -L{{ libpng_location }}/lib' CPPFLAGS='-I{{ libjpeg_location }}/include -I{{ libpng_location }}/include' --prefix={{ graphicsmagick_location }}
    make
    make install
  args:
    chdir: /tmp
    executable: /bin/bash
    creates: /usr/local/bin/gm

- name: Symlink to graphicsmagick library
  file:
    src={{ graphicsmagick_location }}/bin/gm
    dest=/usr/local/bin/gm
    owner=root
    group=root
    state=link

- name: Remove supporting packages
  file:
    path=/tmp/{{ item }}
    state=absent
  with_items:
  - GraphicsMagick-{{ graphicsmagick_version }}
  - GraphicsMagick-{{ graphicsmagick_version }}.tar.gz
