---
#
#  URL: http://sourceforge.net/projects/libjpeg-turbo/files/
#
- name: Uninstall default libjpeg libraries
  apt:
    pkg={{ item }}
    state=absent
    purge=yes
  with_items:
  - libjpeg-turbo8
  - libjpeg8

- name: Determine if new libjpeg folder exists
  stat: path={{ libjpeg_location }}
  register: libjpeg_folder

- name: Download libjpeg
  get_url:
    url={{ libjpeg_url }}
    dest=/tmp/{{ libjpeg_deb }}
    mode=0440
  when: not libjpeg_folder.stat.exists

- name: Install libjpeg
  command: >
    dpkg -i /tmp/{{ libjpeg_deb }}
    creates=/usr/lib/libjpeg.so.62

- name: Symlink to libjpeg library
  file:
    src={{ libjpeg_location }}/lib64/libjpeg.so.62
    dest=/usr/lib/libjpeg.so.62
    owner=root
    group=root
    state=link

- name: Remove deb package
  file:
    path=/tmp/{{ libjpeg_deb }}
    state=absent
