---
#
#  URL: http://sourceforge.net/projects/libpng/files/libpng16/1.6.18/
#
- name: Install zlib
  apt:
    pkg=zlib1g-dev
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}

- name: Determine if libpng folder exists
  stat: path={{ libpng_location }}
  register: libpng_folder

- name: Download libpng
  get_url:
    url={{ libpng_url }}
    dest=/tmp/libpng-{{ libpng_version }}.tar.gz
    mode=0440
  when: not libpng_folder.stat.exists

- name: Unpack and install libpng
  shell: |
    tar -zxvf libpng-{{ libpng_version }}.tar.gz
    cd libpng-{{ libpng_version }}
    ./configure --prefix={{ libpng_location }}
    make
    make install
  args:
    chdir: /tmp
    executable: /bin/bash
    creates: /usr/lib/libpng16.so

- name: Symlink to libpng library
  file:
    src={{ libpng_location }}/lib/libpng16.so
    dest=/usr/lib/libpng16.so
    owner=root
    group=root
    state=link

- name: Remove supporting packages
  file:
    path=/tmp/{{ item }}
    state=absent
  with_items:
  - libpng-{{ libpng_version }}.tar.gz
  - libpng-{{ libpng_version }}
