---
#===============================================================================
#
#  T A S K S / N F S - S E R V E R _ C O N F I G S . Y M L
#
#===============================================================================
- name: Default NFS shared folder
  file:
    path={{ nfs_folder }}
    state=directory
    owner=nobody
    group=nogroup

- name: NFS config
  copy:
    src=etc/{{ item }}
    dest=/etc/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
  - idmapd.conf
  - default/nfs-common
  - default/nfs-kernel-server
  notify: reload nfs-server

- name: Set /etc/exports
  template:
    src=etc/exports.j2
    dest=/etc/exports
    owner=root
    group=root
    mode=0644
  notify: export nfs shares
