---
- name: Copy Sentry HTTP and UDP startup scripts
  copy:
    src=opt/sentry/{{ item }}
    dest=/opt/sentry/
    owner=root
    group=root
    mode=0755
  with_items:
  - sentry_http.sh
  - sentry_udp.sh
  notify:
  - reload sentry http
  - reload sentry udp

- name: Copy Sentry config
  template:
    src=etc/sentry.conf.py.j2
    dest=/etc/sentry.conf.py
    owner=root
    group=root
    mode=0644
  notify:
  - reload sentry http
  - reload sentry udp
