---
#===============================================================================
#
#  T A S K S / L O G R O T A T E . Y M L
#
#===============================================================================
- name: Copy Postgres logrotate config
  copy:
    src=etc/logrotate.d/postgresql-common
    dest=/etc/logrotate.d/
    owner=root
    group=root
    mode=0644
