---
- include: postgres.yml
  tags: [postgres]

# Move postgres location to /opt
- name: Check for new postgres directory
  stat: path={{ postgres_folder }}
  register: new_postgres_dir
  tags: [postgres]

- include: postgres_folder_migration.yml
  when: not new_postgres_dir.stat.exists
  tags: [postgres]

- include: postgres_configs.yml
  tags: [postgres, postgres-configs]

- include: postgres_utils.yml
  tags: [postgres, postgres-utils]

- include: postgres_backup.yml
  tags: [postgres, postgres-backup, backup]

- include: logrotate.yml
  tags: [postgres, postgres-logrotate, logrotate]
