---
- name: Copy Postgres configs
  copy:
    src=etc/postgresql/9.4/main/{{ item }}
    dest=/etc/postgresql/9.4/main/
    owner=postgres
    group=postgres
    mode=0644
    backup=yes
  with_items:
  - environment
  - pg_ctl.conf
  - pg_hba.conf
  - pg_ident.conf
  - postgresql.conf
  notify: reload postgres
