---
- block:
  - name: Install Ansible Pre-requisites
    apt:
      pkg={{ item }}
      state=present
    with_items: "{{ ansible_apt_packages }}"

  - name: Install pip dependencies
    pip:
      name={{ item }}
    with_items: "{{ ansible_pip_packages }}"

  - name: Install Ansible
    pip:
      name=ansible
      version={{ ansible_version_to_install }}

  - name: Create Ansible folder
    file:
      path=/etc/ansible
      state=directory
      owner=root
      group=root

  tags: [ansible]
