---
- name: Add Maven repo
  apt_repository:
    repo='ppa:natecarlson/maven3'
    state=present

- name: Install Maven3
  apt:
    pkg=maven3
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}

- name: Symlink to Maven
  file:
    src=/usr/share/maven3/bin/mvn
    dest=/usr/bin/mvn
    state=link
    owner=root
    group=root
