---
# Add Dev users
- name: Add users folder
  file:
    path=/var/lib/jenkins/users
    state=directory
    owner=jenkins
    group=jenkins
    mode=0755
  notify: reload jenkins

- name: Adding dev user accounts
  file:
    path=/var/lib/jenkins/users/{{ item.firstname }}.{{ item.lastname }}
    state=directory
    owner=jenkins
    group=jenkins
    mode=0755
  with_items: dev_users_list
  notify: reload jenkins

- name: Copy dev user configs
  template:
    src={{ files_dir }}/var/lib/jenkins/user_config.xml.j2
    dest=/var/lib/jenkins/users/{{ item.firstname }}.{{ item.lastname }}/config.xml
    owner=jenkins
    group=jenkins
    mode=0644
  with_items: dev_users_list
  notify: reload jenkins


#
#  DEV USERS
#
- name: Remove all dev users off config.xml
  xml:
     file:    /var/lib/jenkins/config.xml
     xpath:   /hudson/authorizationStrategy/roleMap/role[@name="developer"]/assignedSIDs/sid
     ensure:  absent
  notify: reload jenkins

- name: Add users anew to dev role
  # xml:
  #    file:  /var/lib/jenkins/config.xml
  #    xpath: /hudson/authorizationStrategy/roleMap/role[@name="developer"]/assignedSIDs
  #    add_children:
  #      - sid: "{{ item.username }}"
  # with_items: dev_users_list|sort(attribute='username')
  xml:
     file:  /var/lib/jenkins/config.xml
     xpath: /hudson/authorizationStrategy/roleMap/role[@name="developer"]/assignedSIDs
     add_children:
       - sid: "{{ item.firstname }}.{{ item.lastname }}"
  with_items: dev_users_list|sort(attribute='firstname')
  when: item.teamlead == false
  notify: reload jenkins


#
#  TEAMLEAD USERS
#
- name: Remove all teamlead users off config.xml
  xml:
     file:    /var/lib/jenkins/config.xml
     xpath:   /hudson/authorizationStrategy/roleMap/role[@name="teamlead"]/assignedSIDs/sid
     ensure:  absent
  notify: reload jenkins

- name: Add users anew to teamlead role
  # xml:
  #    file:  /var/lib/jenkins/config.xml
  #    xpath: /hudson/authorizationStrategy/roleMap/role[@name="teamlead"]/assignedSIDs
  #    add_children:
  #      - sid: "{{ item.username }}"
  # with_items: dev_users_list|sort(attribute='username')
  xml:
     file:  /var/lib/jenkins/config.xml
     xpath: /hudson/authorizationStrategy/roleMap/role[@name="teamlead"]/assignedSIDs
     add_children:
       - sid: "{{ item.firstname }}.{{ item.lastname }}"
  with_items: dev_users_list|sort(attribute='firstname')
  when: item.teamlead == true
  notify: reload jenkins
