---
- name: Add users folder
  file:
    path=/var/lib/jenkins/users
    state=directory
    owner=jenkins
    group=jenkins
    mode=0755
  notify: reload jenkins

- name: Adding admin users folders
  file:
    path=/var/lib/jenkins/users/{{ item.firstname }}.{{ item.lastname }}
    state=directory
    owner=jenkins
    group=jenkins
    mode=0755
  with_items: admin_users_list
  notify: reload jenkins

- name: Copy admin user configs
  # template: src={{ files_dir }}/var/lib/jenkins/user_config.xml.j2 dest=/var/lib/jenkins/users/{{ item.username }}/config.xml owner=jenkins group=jenkins mode=0644
  template:
    src=var/lib/jenkins/user_config.xml.j2
    dest=/var/lib/jenkins/users/{{ item.firstname }}.{{ item.lastname }}/config.xml
    owner=jenkins
    group=jenkins
    mode=0644
  with_items: admin_users_list
  notify: reload jenkins

- name: Remove all admin users off config.xml
  xml:
     file:    /var/lib/jenkins/config.xml
     xpath:   /hudson/authorizationStrategy/roleMap/role[@name="admin"]/assignedSIDs/sid
     ensure:  absent
  notify: reload jenkins

- name: Add users anew to admin role
  # xml:
  #    file:  /var/lib/jenkins/config.xml
  #    xpath: /hudson/authorizationStrategy/roleMap/role[@name="admin"]/assignedSIDs
  #    add_children:
  #      - sid: "{{ item.username }}"
  # with_items: admin_users_list|sort(attribute='username')
  xml:
     file:  /var/lib/jenkins/config.xml
     xpath: /hudson/authorizationStrategy/roleMap/role[@name="admin"]/assignedSIDs
     add_children:
       - sid: "{{ item.firstname }}.{{ item.lastname }}"
  with_items: admin_users_list|sort(attribute='firstname')
  notify: reload jenkins
