---
- name: restart postfix
  systemd:
    name: postfix
    state: restarted
    enabled: yes

- name: rebuild aliases.db
  command: /usr/bin/newaliases
  notify: restart postfix

- name: rebuild canonical.db
  command: /usr/sbin/postmap /etc/postfix/canonical
  notify: restart postfix

- name: rebuild sasl_passwd.db
  command: /usr/sbin/postmap /etc/postfix/sasl_passwd
  notify: restart postfix

- name: reload rsyslog
  systemd:
    name: rsyslog
    state: restarted
