---
- name: Check for current FlywayDB
  stat:
    path: "{{ flywaydb_home_directory }}/current"
  register: flywaydb_directory

- name: Add FlywayDB to system-wide $PATH
  copy:
    dest: /etc/profile.d/20-flywaydb.sh
    content: |
      #
      #  FlywayDB environment variable
      #
      export PATH={{ flywaydb_home_directory }}/current:${PATH}
    owner: root
    group: root
    mode: 0755
  when: flywaydb_directory.stat.exists
