---
- name: Add VirtualBox signing key
  apt_key:
    url=http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc
    state=present

- name: Add VirtualBox repo
  apt_repository: >
    repo='deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib'
    state=present

- name: Install VirtualBox
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}
  with_items:
  - build-essential
  - dkms
  - linux-headers-{{ ansible_kernel }}
  - virtualbox-4.3

- name: Add VirtualBox Group
  group:
    name={{ virtualbox_group }}
    state=present

- name: Add VirtualBox User
  user:
    name={{ virtualbox_user }}
    group={{ virtualbox_group }}
    comment="VirtualBox User"
    state=present
