---
- block:
  - name: Check for missing root crontab
    stat:
      path=/var/spool/cron/crontabs/root
    register: crontab_file

  - name: Copy empty crontab template
    template:
      src=tmp/crontab.j2
      dest=/tmp/crontab
      owner=root
      group=root
      mode=0644
    when: not crontab_file.stat.exists

  - name: Copy template to crontab
    shell: >
      cat /tmp/crontab | crontab -
    when: not crontab_file.stat.exists

  - name: Remove crontab template
    file:
      path=/tmp/crontab
      state=absent

  - name: Only record cron errors
    copy:
      src=etc/init/cron.override
      dest=/etc/init/
      owner=root
      group=root
      mode=0644
    notify: reload cron

  - name: Remove unnecessary scheduled cron jobs
    file:
      path=/etc/{{ item }}
      state=absent
    with_items: cron_job_to_remove

  tags: [cron, cron-configs]
