---
- name: Configure cron
  block:

  - name: Check for missing root crontab
    stat:
      path: /var/spool/cron/crontabs/root
    register: crontab_file

  - name: Copy empty crontab template
    template:
      src: crontab.j2
      dest: /tmp/crontab
      owner: root
      group: root
      mode: 0644
    when: not crontab_file.stat.exists

  - name: Copy template to crontab
    shell:
      cat /tmp/crontab | crontab -
    args:
      executable: /bin/bash
    when: not crontab_file.stat.exists

  - name: Remove crontab template
    file:
      path: /tmp/crontab
      state: absent

  - name: Only record cron errors
    copy:
      src: etc/default/cron
      dest: /etc/default
      owner: root
      group: root
      mode: 0644
    notify: restart cron

  - name: Remove unnecessary scheduled cron jobs
    file:
      path: /etc/{{ item }}
      state: absent
    loop: "{{ cron_job_to_remove }}"

  - name: Ensure systemd restarts cron
    lineinfile:
      dest: /lib/systemd/system/cron.service
      regexp: '^Restart'
      insertafter: '\[Service\]'
      line: 'Restart=always'

  tags: [cron]
