---
podman_required_pkgs:
- btrfs-tools
- git
- golang-go
- go-md2man
- iptables
- libassuan-dev
- libc6-dev
- libdevmapper-dev
- libglib2.0-dev
- libgpgme-dev
- libgpg-error-dev
- libostree-dev
- libprotobuf-dev
- libprotobuf-c0-dev
- libseccomp-dev
- libselinux1-dev
- libsystemd-dev
- pkg-config
- runc
- software-properties-common
- uidmap

podman_repo: ppa:projectatomic/ppa
