---
- name: Uninstall Packages
  apt:
    pkg={{ item }}
    state=absent
    purge=yes
  with_items: "{{ apt_packages_to_remove }}"

- name: Remove files for uninstalled packages
  file:
    path={{ item }}
    state=absent
  with_items:
  - /var/log/chef
  - /var/log/puppet
  - /var/log/pppconfig

- name: Set apt no-recommends
  copy:
    src=etc/apt/apt.conf.d/no-recommends
    dest=/etc/apt/apt.conf.d
    owner=root
    group=root
    mode=0644

- name: Update apt caches
  apt:
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}

- name: Install default packages
  apt:
    pkg={{ item }}
    state=present
  with_items: "{{ apt_packages_to_install }}"
  notify:
  - stop and disable rsync
  - stop and disable sysstat

- name: Enable HTTPS transport for apt
  apt:
    pkg=apt-transport-https
    state=present

- name: Install optional packages
  apt:
    pkg={{ item }}
    state=present
  with_items: "{{ apt_packages_optional }}"
  when: apt_install_optional == True

- name: Force notify to run now
  meta: flush_handlers
