---
- name: Create company folder
  file:
    path=/opt/{{ company_name }}
    state=directory
    owner=root
    group=root

- name: List of files on company folder
  local_action: command ls -1 {{ role_path }}/files/opt/{{ company_name }}/
  become: false
  changed_when: false
  register: script_files

- name: Copy files to company folder
  copy:
    src=opt/{{ company_name }}/{{ item }}
    dest=/opt/{{ company_name }}/
    owner=root
    group=root
  with_items: "{{ script_files.stdout_lines }}"

# - name: Create multiple extension string
#   set_fact:
#     extensions: "{{ executable_ext | join('\|') }}"

# - name: List of scripts
#   shell: |
#       ls -1 *.{%raw%}{{%endraw%}{{ extensions }}{%raw%}}{%endraw%}
#   args:
#     chdir: /opt/{{ company_name }}
#   register: executable_files
#   changed_when: false
#   ignore_errors: yes

# - debug:
#     var: executable_files

# - name: Set scripts to be executable
#   # shell: >
#   #   chmod 0755 /opt/{{ company_name }}/*.{{ item }}
#   # changed_when: false
#   # with_items: [ py, rb, js, sh ]
#   # ignore_errors: yes
#   file:
#     path: /opt/{{ company_name }}/{{ item }}
#     mode: "u+x"
#   with_items: "{{ executable_files.stdout_lines }}"
