---
- name: Configure logrotate
  block:

  - name: Copy logrotate config
    copy:
      src: etc/logrotate.conf
      dest: /etc/
      owner: root
      group: root
      mode: 0644

  tags: [logrotate]
