---
#
#  Gem versions:
#  - gem1.8
#  - gem1.9.3 [really 1.9.1]
#  - gem2.4
#
- name: Install 1.8 gems
  gem:
    name={{ item }}
    user_install=no
    executable=/usr/bin/gem1.8
    state=present
  with_items: "{{ gems_1_8 }}"

- name: Install 1.9.3 gems
  gem:
    name={{ item }}
    user_install=no
    executable=/usr/bin/gem1.9.3
    state=present
  with_items: "{{ gems_1_9_3 }}"

- name: Install 2.4 gems
  gem:
    name={{ item }}
    user_install=no
    executable=/usr/bin/gem2.4
    state=present
  with_items: "{{ gems_2_4 }}"
