---
#
#  Using brightbox deb packages:
#  URL: https://www.brightbox.com/docs/ruby/ubuntu/
#
- name: Install Ruby pre-requisites packages
  apt:
    pkg: "{{ ruby_pre_pkgs }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_time }}"

- name: Add BrightBox Ruby repo
  apt_repository:
    repo: "{{ ruby_repo }}"
    state: present

- name: Install Ruby packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_time }}"
  loop: "{{ ruby_pkgs }}"

- name: Set default ruby version
  command: >
    ruby-switch --set {{ ruby_default_version }}
  changed_when: False
