---
#
#  Using brightbox deb packages:
#  URL: https://www.brightbox.com/docs/ruby/ubuntu/
#
- name: Install Ruby pre-requisites packages
  apt:
    pkg=build-essential
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}

- name: Add BrightBox Ruby repo
  apt_repository:
    repo='ppa:brightbox/ruby-ng'
    state=present

- name: Install/upgrade Ruby packages
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}
  with_items: "{{ ruby_default_packages }}"

- name: Set default ruby version
  command: >
    ruby-switch --set {{ ruby_default_version }}
  changed_when: False
