---
- name: Add NGINX PPA
  apt_repository:
    repo='ppa:nginx/stable'
    state=present

- name: Install NGINX
  apt:
    pkg=nginx
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}

- name: Ensure all nginx sites directories exist
  file:
    path=/etc/nginx/sites-{{ item }}
    state=directory
    owner=root
    group=root
    mode=0755
  with_items:
  - enabled
  - available
