---
- name: Install Maven
  block:

  - name: Ensure Java 11 is installed
    import_role:
      name: development/java_11

  - name: Add Maven repo
    apt_repository:
      repo: 'ppa:andrei-pozolotin/maven3'
      state: present

  - name: Install Maven
    apt:
      pkg: maven
      state: present
      update_cache: yes
      cache_valid_time: "{{ apt_cache_time }}"

  tags: [maven3]
