---
- name: Install Icinga pre-requisites packages
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}
  with_items: icinga_apt_requirements
  notify: reload apache

- name: Add Icinga Repo
  apt_repository:
    repo='ppa:formorer/icinga'
    state=present

- name: Set idoutils to use MySQL
  debconf:
    name='icinga-idoutils'
    question='icinga-idoutils/database-type'
    value='mysql'
    vtype='select'

- name: Install Icinga Packages
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}
  with_items: icinga_pkgs
  notify:
  - reload apache
  - reload icinga
  - reload ido2db
  environment:
    DEBIAN_FRONTEND: noninteractive

#
# Complete enabling external commands on Icinga
#
- name: Slurp /var/lib/dpkg/statoverride
  slurp:
    src=/var/lib/dpkg/statoverride
  register: override_file

- name: Add /var/lib/icinga* if missing on statoverride file
  command: dpkg-statoverride --update --add {{ item }}
  with_items:
  - "nagios www-data 2710 /var/lib/icinga/rw"
  - "nagios nagios 751 /var/lib/icinga"
  when: (override_file.content | b64decode | search("{{ item }}")) == False
  notify: reload icinga
