---
- name: Copy default etc config
  copy:
    src=etc/default/icinga
    dest=/etc/default/
    owner=root
    group=root
    mode=0644
  notify: reload icinga

- name: Copy static global configs
  copy:
    src=etc/icinga/{{ item }}
    dest=/etc/icinga/
    owner=root
    group=root
    mode=0644
  with_items:
  - icinga.cfg
  - cgi.cfg
  notify: reload icinga

- name: Copy dynamic global configs
  template:
    src=etc/icinga/{{ item }}.j2
    dest=/etc/icinga/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
  - resource.cfg
  - commands.cfg
  notify: reload icinga

- name: Copy ido2db module cfg
  copy:
    src=etc/icinga/modules/idoutils.cfg
    dest=/etc/icinga/modules/
    owner=root
    group=root
    mode=0644
  notify:
  - reload icinga
  - reload ido2db

- name: Copy htpwds credentials
  template:
    src=etc/icinga/icinga-pwds.j2
    dest=/etc/icinga/icinga-pwds
    owner=root
    group=root
    mode=0644
  notify: reload apache

- name: Copy Apache conf
  copy:
    src=etc/icinga/apache2.conf
    dest=/etc/icinga/
    owner=root
    group=root
    mode=0644
  notify: reload apache

- name: Copy Apache Redirect
  copy:
    src=etc/apache2/sites-available/icinga-redirect.conf
    dest=/etc/apache2/sites-available/
    owner=root
    group=root
    mode=0644
  notify: reload apache

- name: Enable Icinga Redirect
  command: >
    a2ensite icinga-redirect.conf
    creates=/etc/apache2/sites-enabled/icinga-redirect.conf
  notify: reload apache

- name: Copy and enable monit check
  copy:
    src=etc/monit/conf.d/icinga.conf
    dest=/etc/monit/conf.d/
    owner=root
    group=root
    mode=0644
  notify: reload monit
  tags:
  - monit
  - icinga-configs
