---
- name: Install MKLiveStatus pre-requisites packages
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}
  with_items: mklivestatus_apt_requirements

- name: Check for MKLiveStatus install
  stat: path=/opt/omd/versions/1.2.6p9.cre/share/doc/check_mk/livestatus
  register: mklivestatus_file

- name: Download MKLiveStatus U14.04 deb package
  get_url:
    url={{ mklivestatus_package_location }}/{{ mklivestatus_package_file }}
    dest=/tmp/{{ mklivestatus_package_file }}
  register: downloaded
  when: not mklivestatus_file.stat.exists

- name: Install MKLiveStatus U14.04 deb package
  apt:
    deb=/tmp/{{ mklivestatus_package_file }}
  when: not mklivestatus_file.stat.exists and downloaded|success

- name: Copy mklivestatus cfg
  copy:
    src=etc/icinga/modules/mklivestatus.cfg
    dest=/etc/icinga/modules/
    owner=root
    group=root
    mode=0644
  notify: reload icinga

- name: Remove downloaded package
  file:
    path=/tmp/{{ mklivestatus_package_file }}
    state=absent
