---
- name: Install Nagios API pre-requisites deb packages
  apt:
    pkg={{ item }}
    state=present
  with_items:
  - python-dev
  - libffi-dev

- name: Install Nagios API pre-requisites pip packages
  pip:
    name={{ item }}
    state=present
  with_items:
  - diesel
  - greenlet
  - pyopenssl

- name: Install Nagios API
  git:
    repo=https://github.com/zorkian/nagios-api.git
    dest=/opt/nagios-api
    version=master
    update=no

- name: Copy Nagios API init.d script
  copy:
    src=etc/init.d/nagios-api
    dest=/etc/init.d/
    owner=root
    group=root
    mode=0755

- name: Enable Nagios API init.d daemon
  command: >
    sysv-rc-conf nagios-api on
    creates=/etc/rc2.d/S20nagios-api

- name: Copy and enable Nagios API monit check
  copy:
    src=etc/monit/conf.d/nagios-api.conf
    dest=/etc/monit/conf.d/
    owner=root
    group=root
    mode=0644
  notify: reload monit
  tags: monit
