---
- name: Add PagerDuty Key
  apt_key:
    url=http://packages.pagerduty.com/GPG-KEY-pagerduty
    state=present

- name: Add PagerDuty Repo
  apt_repository:
    repo='deb http://packages.pagerduty.com/pdagent deb/'
    state=present

- name: Install Pagerduty agent
  apt:
    pkg={{ item }}
    state=latest
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}
  with_items:
  - pdagent
  - pdagent-integrations

- name: Copy PagerDuty contacts to Icinga
  template:
    src=etc/icinga/r29/contacts/pagerduty.cfg.j2
    dest=/etc/icinga/r29/contacts/pagerduty.cfg
    owner=root
    group=root
    mode=0644
  notify: reload icinga

- name: Copy and enable monit pdagent check
  copy:
    src=etc/monit/conf.d/pdagent.conf
    dest=/etc/monit/conf.d/
    owner=root
    group=root
    mode=0644
  notify: reload monit
  tags: monit
