---
- name: Install pnp4nagios package
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}
  with_items:
  - pnp4nagios
  - librrds-perl
  - rrdtool

- name: pnp4nagios default etc config
  copy:
    src=etc/default/npcd
    dest=/etc/default/
    owner=root
    group=root
    mode=0644
  notify:
  - reload pnp4nagios
  - reload icinga

- name: Copy pnp4nagios configs
  copy:
    src=etc/pnp4nagios/{{ item }}
    dest=/etc/pnp4nagios/
    owner=root
    group=root
    mode=0644
  with_items:
  - apache.conf
  - config.php
  - npcd.cfg
  notify:
  - reload pnp4nagios
  - reload icinga

- name: List of local pnp4nagios templates
  local_action: command ls -1 {{ role_path }}/files/etc/pnp4nagios/templates/
  register: pnp4nagios_files
  changed_when: False
  sudo: no
  tags:
  - pnp4nagios-templates
  - icinga-configs

- name: pnp4nagios templates
  copy:
    src=etc/pnp4nagios/templates/{{ item }}
    dest=/etc/pnp4nagios/templates/
    owner=root
    group=root
    mode=0644
  with_items: pnp4nagios_files.stdout_lines
  notify: reload pnp4nagios
  tags:
  - pnp4nagios-templates
  - icinga-configs

- name: pnp4nagios ssi files
  copy:
    src=usr/share/icinga/htdocs/ssi/common-header.ssi
    dest=/usr/share/icinga/htdocs/ssi/
    owner=root
    group=root
    mode=0644

- name: Copy fancybox folder
  unarchive:
    src=tmp/fancybox.tar.gz
    dest=/usr/share/icinga/htdocs
    copy=yes

- name: Copy pnp4nagios custom php files
  copy:
    src=usr/share/pnp4nagios/html/application/{{ item }}
    dest=/usr/share/pnp4nagios/html/application/
    owner=root
    group=root
    mode=0644
  with_items:
  - controllers/graph.php
  - controllers/system.php
  - views/graph_tiny.php
  - views/icon_box.php

- name: Enable pnp4nagios module on Icinga
  copy:
    src=etc/icinga/modules/pnp4nagios.cfg
    dest=/etc/icinga/modules/
    owner=root
    group=root
    mode=0644
  notify:
  - reload pnp4nagios
  - reload icinga

- name: Symlink pnp4nagios Apache conf
  file:
    src=/etc/pnp4nagios/apache.conf
    dest=/etc/apache2/sites-enabled/pnp4nagios.conf
    owner=root
    group=root
    state=link
  notify: reload apache
