---
- name: Install Slack pre-requisites packages
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}
  with_items:
  - libwww-perl
  - libcrypt-ssleay-perl

- name: Copy Slack perl script
  template:
    src=usr/local/bin/slack_icinga.pl.j2
    dest=/usr/local/bin/slack_icinga.pl
    owner=root
    group=root
    mode=0755

- name: Copy Slack contacts to Icinga
  template:
    src=etc/icinga/r29/contacts/slack.cfg.j2
    dest=/etc/icinga/r29/contacts/slack.cfg
    owner=root
    group=root
    mode=0644
  notify: reload icinga
