---
- name: Configure PAM
  block:

  - name: List of pam.d configs
    command:
      ls -1 "{{ role_path }}/files/etc/pam.d/"
    delegate_to: localhost
    changed_when: false
    become: false
    register: pamd_files

  - name: Copy pam.d configs
    copy:
      src: "etc/pam.d/{{ item }}"
      dest: /etc/pam.d/
      owner: root
      group: root
      mode: 0644
    loop: "{{ pamd_files.stdout_lines }}"

  - name: Install password strength checker
    apt:
      pkg: passwdqc
      state: present
      update_cache: yes
      cache_valid_time: "{{ apt_cache_time }}"

  tags: [pam]
