---
#
#  CURATOR: https://github.com/elasticsearch/elasticsearch-cloud-aws
#
- name: Install curator for index pruning
  pip:
    name=elasticsearch-curator
    state=present
  tags: curator

- name: Enable pruning thru global /etc/cron.d
  cron:
    name="elasticsearch prune indeces"
    cron_file=elasticsearch_curator
    state=present
    user="root"
    hour="4"
    minute="{{ 55 | random(step=5) }}"
    job="/usr/local/bin/curator --host 127.0.0.1 -d {{ curator_delete_days }} -c {{ curator_close_days }} 2>&1 | /usr/bin/logger -t elasticsearch_curator"
  changed_when: False
  tags: curator
