---
- name: Copy all elasticsearch configs
  copy:
    src={{ item }}
    dest=/{{ item }}
    owner=root
    group=root
    mode=0644
  with_items:
  - etc/default/elasticsearch
  - etc/elasticsearch/elasticsearch.yml
  - etc/elasticsearch/logging.yml

- name: Copy elasticsearch limits.conf
  copy:
    src=etc/security/limits.d/10-elasticsearch.conf
    dest=/etc/security/limits.d/
    owner=root
    group=root
    mode=0644

- name: Copy elasticsearch init.d
  copy:
    src=etc/init.d/elasticsearch
    dest=/etc/init.d/
    owner=root
    group=root
    mode=0755

- lineinfile: dest=/etc/init.d/elasticsearch regexp='^(DAEMON_OPTS=".*-Des.max-open-files=true")$' insertafter='^(DAEMON_OPTS=".*CONF_DIR")$' line='DAEMON_OPTS="$DAEMON_OPTS -Des.max-open-files=true"'
  notify: Restart Elasticsearch
