---
- block:
  - name: Install latest SSH
    apt:
      pkg=openssh-server
      state=latest
      update_cache=yes
      cache_valid_time={{ apt_cache_time }}

  - name: Copy global sshd_config
    copy:
      src=etc/ssh/sshd_config
      dest=/etc/ssh/
      owner=root
      group=root
      mode=0444

  notify: reload ssh
  tags: [ssh]
