---
- block:
  - name: Check for existing installation
    stat: path="{{ composer_bin }}"
    register: composer_phar

  - name: Download Composer
    get_url:
      url={{ composer_url }}
      dest=/tmp/composer_installer
      mode=0440
    when: not composer_phar.stat.exists

  - name: Install Composer
    shell: >
      php -f /tmp/composer_installer
      creates=/tmp/composer.phar

  - name: Move Composer to global path
    file:
      path=/tmp/composer.phar
      dest="{{ composer_bin }}"
      owner=root
      group=root
      mode=0755

  tags: [composer]
