---
- name: ClamAV config
  copy:
    src: etc/clamav/clamd.conf
    dest: /etc/clamav/
    owner: root
    group: root
    mode: 0644
  notify: restart clamav

- name: FreshClam config
  copy:
    src: etc/clamav/freshclam.conf
    dest: /etc/clamav/
    owner: clamav
    group: adm
    mode: 0444
  notify: restart freshclam
