---
- block:
  - name: Add Maven repo
    apt_repository:
      repo='ppa:andrei-pozolotin/maven3'
      state=present

  - name: Install Maven3
    apt:
      pkg=maven3
      state=present
      update_cache=yes
      cache_valid_time={{ apt_cache_time }}

  tags: [maven3]
