---
- block:
  - name: Add Groovy repo
    apt_repository:
      repo='ppa:groovy-dev/groovy'
      state=present

  - name: Install Groovy
    apt:
      pkg=groovy
      state=present
      update_cache=yes
      cache_valid_time={{ apt_cache_time }}

  tags: [groovy]
