---
#
#  Ephemeral volume
#
- name: Check for Ephemeral disk
  command:
    mountpoint -x /dev/xvdb
  ignore_errors: true
  changed_when: false
  register: xvdb_exists

- name: Optimize ephemeral disk on /etc/fstab
  mount:
    name: /mnt
    src: /dev/xvdb
    fstype: auto
    opts: defaults,nofail,x-systemd.device-timeout=10,noatime,nodiratime,x-systemd.requires=cloud-init.service,comment=cloudconfig
    passno: '2'
    dump: '0'
    state: present
  when: xvdb_exists.rc == 0

#
#  EBS app volume
#
- name: Ensure /apps exists
  file:
    path: /apps
    state: directory
    owner: root
    group: root

- name: Check for EBS disk
  command:
    mountpoint -x /dev/xvdc
  ignore_errors: true
  changed_when: false
  register: xvdc_exists

- name: Configure EBS disk
  block:

  - name: Format EBS disk
    filesystem:
      fstype: ext4
      dev: /dev/xvdc

  - name: Add EBS disk to /etc/fstab
    mount:
      name: /apps
      src: /dev/xvdc
      fstype: ext4
      opts: defaults,nofail,x-systemd.device-timeout=10,noatime,nodiratime
      passno: '0'
      dump: '0'
      state: present

  when: xvdc_exists.rc == 0
