---
- name: Install AWS pip utilities
  pip:
    name: "{{ aws_pip_pkgs }}"
    state: present

- name: Install AWS apt utilities
  apt:
    pkg: "{{ aws_apt_pkgs }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_time }}"

- name: Set AWS cli default region
  command: "aws configure set region {{ aws_default_region }}"
  changed_when: false

- name: Set AWS cli default output
  command: "aws configure set output {{ aws_default_output }}"
  changed_when: false
