---
- name: Copy collectd daemon configs
  copy:
    src=etc/collectd/{{ item }}
    dest=/etc/collectd/
    owner=root
    group=root
    mode=0644
  with_items: collectd_default_configs
  notify: reload collectd

- name: Copy collectd server config
  copy:
    src=etc/collectd/conf.d/network_server.conf
    dest=/etc/collectd/conf.d/
    owner=root
    group=root
    mode=0644
  when: '"collectd" in group_names'
  notify: reload collectd

- name: Copy collectd client config
  copy:
    src=etc/collectd/conf.d/network_client.conf
    dest=/etc/collectd/conf.d/
    owner=root
    group=root
    mode=0644
  when: '"collectd" not in group_names'
  notify: reload collectd

- name: Copy other service configs
  copy:
    src=etc/collectd/conf.d/{{ item }}
    dest=/etc/collectd/conf.d/
    owner=root
    group=root
    mode=0644
  with_items: collectd_other_configs
  notify: reload collectd

- name: Copy custom db types
  copy:
    src=etc/collectd/custom_types.db_
    dest=/etc/collectd/custom_types.db
    owner=root
    group=root
    mode=0644
