---
- name: Uninstall default MySQL
  apt:
    pkg={{ item }}
    state=absent
    purge=yes
  with_items:
  - mysql-common
  - mysql-server

- name: Add Percona signing key
  apt_key:
    url=http://www.percona.com/downloads/RPM-GPG-KEY-percona
    state=present
  tags: repo

- name: Add Percona repo
  apt_repository:
    repo='deb http://repo.percona.com/apt precise main'
    state=present
  tags: repo

- name: Install Percona MySQL packages
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time={{ apt_cache_time }}
  with_items: mysql_apt_packages
  environment:
    DEBIAN_FRONTEND: noninteractive
