---
- name: Create mysql users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default(false) or item.mysql_host }}"
    password: "{{ item.password|default(false) or item.mysql_password }}"
    priv: "{{ item.priv | default(false) or item.mysql_priv }}"
    state: "{{ item.state | default(false) or 'present' }}"
  loop: "{{ mysql_users }}"

- name: Ensure Anonymous user(s) are not in the database
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
  loop:
  - localhost
  - "{{ ansible_hostname }}"
