---
- block:
  - name: Install NodeJS pre-requisites
    apt:
      pkg=build-essential
      state=present
      update_cache=yes
      cache_valid_time={{ apt_cache_time }}

  - name: Add NodeJS key
    apt_key:
      url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state=present

  - name: Add NodeJS repo
    apt_repository:
      repo='deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
      state=present

  - name: Add NodeJS repo preferences
    copy:
      src=etc/apt/preferences.d/deb_nodesource_com_node.pref
      dest=/etc/apt/preferences.d/
      owner=root
      group=root
      mode=0644

  - name: Install NodeJS
    apt:
      pkg=nodejs
      state=present
      update_cache=yes
      cache_valid_time={{ apt_cache_time }}

  tags: [nodejs]
