---
- name: Check for Kibana link
  stat: path=/opt/kibana
  register: kibana_link

- name: Download Kibana
  get_url:
    url={{ kibana_url }}/{{ kibana_file }}
    dest=/tmp/{{ kibana_file }}
  register: kibana_download
  when: not kibana_link.stat.exists

- name: Install Kibana
  unarchive:
    src=/tmp/{{ kibana_file }}
    dest=/opt
    owner=root
    group=root
    copy=no
  when: not kibana_link.stat.exists and kibana_download|changed

- name: Symlink Kibana directory
  file:
    src="/opt/{{ kibana_folder }}"
    dest=/opt/kibana
    owner=root
    group=root
    state=link

- name: Remove Kibana install file
  file:
    path=/tmp/{{ kibana_file }}
    state=absent
