---
- name: Copy all mongodb configs
  copy:
    src=etc/{{ item }}
    dest=/etc/
    owner=root
    group=root
    mode=0644
  with_items:
  - mongod_master.conf
  - mongod_slave.conf
  - mongod_standalone.conf

- name: Check for original MongoDB config
  stat: path=/etc/mongod.conf
  register: mongodb_link

- name: Backup original mongod.conf
  command: >
    mv /etc/mongod.conf /etc/mongod.conf.original
  when: mongodb_link.stat.exists and not mongodb_link.stat.islnk

- name: Enable stand-alone mongodb
  file:
    src=/etc/mongod_standalone.conf
    dest=/etc/mongod.conf
    owner=root
    group=root
    state=link
  when: mongodb_link.stat.exists and not mongodb_link.stat.islnk
  notify: reload mongodb
