---
- name: Stop MongoDB
  service:
    name=mongod
    state=stopped

- name: Wait for mongod to completely stop
  wait_for:
    port=27017
    delay=10
    state=stopped

- name: Move MongoDB to new location
  shell: >
    mv /var/lib/mongodb {{ mongodb_folder }}
    creates="{{ mongodb_folder }}"

- name: Move db.x files to their own folders
  shell: |
    cd {{ mongodb_folder }}
    mkdir -p {{ item }}
    mv {{ item }}.* {{ item }}/.
    chown -R mongodb:nogroup {{ item }}
    creates={{ mongodb_folder }}/{{ item }}/
    removes={{ mongodb_folder }}/{{ item }}.ns
  with_items:
  - local

- name: Link to new mongodb location
  file:
    src={{ mongodb_folder }}
    dest=/var/lib/mongodb
    owner=mongodb
    group=mongodb
    state=link

- name: Start MongoDB
  service:
    name=mongod
    state=started

- name: Wait for mongod to completely start
  wait_for:
    port=27017
    delay=10
    state=started
