---
galaxy_info:
  author: Israel Farfan
  description: Install PHP-FPM
  company: IXF
  license: GPLv3
  min_ansible_version: 1.9.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - cloud
  - system
  - web

dependencies:
- role: development/php
  has_extended_packages: True
