---
- hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: Install python3, if not present
    raw: bash -c "test -e /usr/bin/python3 || (apt -qqy update && apt install -qqy python3-minimal)"
    register: output
    changed_when: output.stdout not in ["", "\r\n"]
