---
- hosts: all
  become: true
  gather_facts: false

  tasks:
  - name: Check if automatic reboot is required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Kick-in automatic reboot
    block:

    - name: Rebooting system
      shell: >
        sleep 5; shutdown -r now 'Rebooting to complete system upgrade'
      ignore_errors: true
      async: 5
      poll: 0
      changed_when: false

    - name: Waiting for machine to come back
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300

    when: reboot_required_file.stat.exists
