---
- name: Add WireGuard repo
  apt_repository:
    repo: 'ppa:wireguard/wireguard'
    state: present

- name: Install WireGuard
  apt:
    pkg: "{{ wireguard_pkgs }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_time }}"
