---
#
#  C O N S U L T A N T S
#
#  Consultants are only allowed on 'dev' and 'local'
#
- name: Adding Consultant users accounts
  user:
    name: "{{ item.username }}"
    shell: '/bin/bash'
    comment: "{{ item.firstname }} {{ item.lastname }}"
  loop: "{{ users_consultant }}"
  when: environment_name in ['local', 'development']

- name: Adding Consultant users ssh keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_keys | join('\n') }}"
    exclusive: yes
  loop: "{{ users_consultant }}"
  when: environment_name in ['local', 'development']

- name: Sudoers file for Consultant Users, but not on MGM servers
  template:
    src: etc/sudoers.d/25-consultants.j2
    dest: /etc/sudoers.d/25-consultants
    owner: root
    group: root
    mode: 0440
  when: environment_name in ['local', 'development'] and 'mgm' not in group_names and users_consultant
