---
#
#  R E M O V E   U S E R S
#
- name: Removing User Home Folders
  file:
    path: "/home/{{ item }}"
    state: absent
  loop: "{{ disabled_users }}"

- name: Removing User Accounts
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  loop: "{{ disabled_users }}"
