---
- name: Install PHP
  apt:
    pkg={{ item }}
    state=present
  with_items:
  - php5
  - php5-cli

- name: Copy php.ini
  copy:
    src=etc/php5/apache2/php.ini
    dest=/etc/php5/apache2/
    owner=root
    group=root
    mode=0644
  notify: reload apache
  tags: apache-configs
