---
- name: Overwrite original deflate mod config
  copy:
    src=etc/apache2/mods-available/deflate.conf
    dest=/etc/apache2/mods-available/
    owner=root
    group=root
    mode=0644
  notify: reload apache

- name: Enable Apache mods
  command: >
    a2enmod {{ item }}
    creates=/etc/apache2/mods-enabled/{{ item }}.load
  with_items: apache_enabled_mods
  notify: reload apache

- name: Disable Apache mods
  command: >
    a2dismod {{ item }}
    removes=/etc/apache2/mods-enabled/{{ item }}.load
  with_items: apache_disabled_mods
  notify: reload apache
